[package]
name = "sky-sl"
version = "0.1.0"
authors = ["Andreas Fischer <opensource@deviru.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-xid = "0.2"
text-size = "1.1"
rowan = "0.12"
